version: "3.8"

services:
  db:
    image: postgres:alpine3.18
    container_name: db-postgre
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=postgres"
    restart: always
    ports:
      - "5431:5432"
    networks:
      challenge_network:


  ms-auth-and-auto:
    depends_on:
      - db
    build: ./auth-and-auto
    ports:
      - "8080:8080"
    container_name: app-central
    networks:
      challenge_network:
        ipv4_address: 172.23.0.3

    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=1234"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"

  ms-scholar-a:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./scholar-a
    ports:
      - '8081:8081'
    container_name: app-individual
    networks:
      challenge_network:
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

networks:
  challenge_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1