version: "3.8"

services:
  db:
    image: postgres:alpine3.18
    container_name: db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=postgres"
    restart: always
    ports:
      - "5431:5432"


  ms-auth-and-auto:
    depends_on:
      - db
    build: ./auth-and-auto
    ports:
      - "8080:8080"
    container_name: app
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=1234"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"
