version: "3.8"

services:
  db:
    image: postgres:alpine3.18
    container_name: db-postgre
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=postgres"
    restart: always
    networks:
      challenge:
        ipv4_address: 172.23.0.2
    ports:
      - "5431:5432"

  ms-auth-and-auto:
    depends_on:
      - db
    build: ./auth-and-auto
    ports:
      - "8080:8080"
    container_name: app-central
    networks:
      challenge:
        ipv4_address: 172.23.0.3
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=1234"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"

  ms-scholar-a:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./scholar-a
    ports:
      - '8081:8081'
    container_name: app-individual-a
    networks:
      challenge:
        ipv4_address: 172.23.0.4
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  ms-scholar-b:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./scholar-b
    ports:
      - '8082:8082'
    container_name: app-individual-b
    networks:
      challenge:
        ipv4_address: 172.23.0.5
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  ms-scholar-d:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./scholar-d
    ports:
      - '8084:8084'
    container_name: app-individual-d
    networks:
      challenge:
        ipv4_address: 172.23.0.6

    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  ms-scholar-e:
      depends_on:
        - db
        - ms-auth-and-auto
      build: ./scholar-e
      ports:
        - '8085:8085'
      container_name: app-individual-e
      networks:
        challenge:
          ipv4_address: 172.23.0.7

      environment:
        - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
        - 'SPRING_DATASOURCE_USERNAME=postgres'
        - 'SPRING_DATASOURCE_PASSWORD=1234'
        - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

networks:
  challenge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
