version: "3.8"

services:
  db:
    image: postgres:alpine3.18
    container_name: db-postgre
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=postgres"
    restart: always
    ports:
      - "5431:5432"


  ms-auth-and-auto:
    depends_on:
      - db
    build: ./auth-and-auto
    ports:
      - "8080:8080"
    container_name: app-central
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=1234"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"

  ms-scholar-a:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./ms-scholar-a
    ports:
      - '8081:8081'
    container_name: app-individual
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
  ms-scholar-b:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./ms-scholar-b
    ports:
      - '8082:8082'
    container_name: app-individual
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  ms-scholar-c:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./ms-scholar-c
    ports:
      - '8083:8083'
    container_name: app-individual
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  ms-scholar-d:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./ms-scholar-d
    ports:
      - '8084:8084'
    container_name: app-individual
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  ms-scholar-e:
    depends_on:
      - db
      - ms-auth-and-auto
    build: ./ms-scholar-e
    ports:
      - '8085:8085'
    container_name: app-individual
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

